# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from ecom_agent.v1 import ecom_env_pb2 as ecom__agent_dot_v1_dot_ecom__env__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ecom_agent/v1/ecom_env_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EcomEnvStub:
    """EcomEnv is the Playground surface: agent-working tools over an isolated
    per-playground filesystem. Mirrors the bitgn EcomRuntime env-tool subset.
    Deliberately excludes any benchmark-specific RPC (no `answer`, no scoring).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Read = channel.unary_unary(
                '/ecom_agent.v1.EcomEnv/Read',
                request_serializer=ecom__agent_dot_v1_dot_ecom__env__pb2.ReadRequest.SerializeToString,
                response_deserializer=ecom__agent_dot_v1_dot_ecom__env__pb2.ReadResponse.FromString,
                _registered_method=True)
        self.ReadSilent = channel.unary_unary(
                '/ecom_agent.v1.EcomEnv/ReadSilent',
                request_serializer=ecom__agent_dot_v1_dot_ecom__env__pb2.ReadRequest.SerializeToString,
                response_deserializer=ecom__agent_dot_v1_dot_ecom__env__pb2.ReadResponse.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/ecom_agent.v1.EcomEnv/List',
                request_serializer=ecom__agent_dot_v1_dot_ecom__env__pb2.ListRequest.SerializeToString,
                response_deserializer=ecom__agent_dot_v1_dot_ecom__env__pb2.ListResponse.FromString,
                _registered_method=True)
        self.Tree = channel.unary_unary(
                '/ecom_agent.v1.EcomEnv/Tree',
                request_serializer=ecom__agent_dot_v1_dot_ecom__env__pb2.TreeRequest.SerializeToString,
                response_deserializer=ecom__agent_dot_v1_dot_ecom__env__pb2.TreeResponse.FromString,
                _registered_method=True)
        self.Find = channel.unary_unary(
                '/ecom_agent.v1.EcomEnv/Find',
                request_serializer=ecom__agent_dot_v1_dot_ecom__env__pb2.FindRequest.SerializeToString,
                response_deserializer=ecom__agent_dot_v1_dot_ecom__env__pb2.FindResponse.FromString,
                _registered_method=True)
        self.Search = channel.unary_unary(
                '/ecom_agent.v1.EcomEnv/Search',
                request_serializer=ecom__agent_dot_v1_dot_ecom__env__pb2.SearchRequest.SerializeToString,
                response_deserializer=ecom__agent_dot_v1_dot_ecom__env__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.Stat = channel.unary_unary(
                '/ecom_agent.v1.EcomEnv/Stat',
                request_serializer=ecom__agent_dot_v1_dot_ecom__env__pb2.StatRequest.SerializeToString,
                response_deserializer=ecom__agent_dot_v1_dot_ecom__env__pb2.StatResponse.FromString,
                _registered_method=True)
        self.Exec = channel.unary_unary(
                '/ecom_agent.v1.EcomEnv/Exec',
                request_serializer=ecom__agent_dot_v1_dot_ecom__env__pb2.ExecRequest.SerializeToString,
                response_deserializer=ecom__agent_dot_v1_dot_ecom__env__pb2.ExecResponse.FromString,
                _registered_method=True)
        self.Write = channel.unary_unary(
                '/ecom_agent.v1.EcomEnv/Write',
                request_serializer=ecom__agent_dot_v1_dot_ecom__env__pb2.WriteRequest.SerializeToString,
                response_deserializer=ecom__agent_dot_v1_dot_ecom__env__pb2.WriteResponse.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/ecom_agent.v1.EcomEnv/Delete',
                request_serializer=ecom__agent_dot_v1_dot_ecom__env__pb2.DeleteRequest.SerializeToString,
                response_deserializer=ecom__agent_dot_v1_dot_ecom__env__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.Context = channel.unary_unary(
                '/ecom_agent.v1.EcomEnv/Context',
                request_serializer=ecom__agent_dot_v1_dot_ecom__env__pb2.ContextRequest.SerializeToString,
                response_deserializer=ecom__agent_dot_v1_dot_ecom__env__pb2.ContextResponse.FromString,
                _registered_method=True)


class EcomEnvServicer:
    """EcomEnv is the Playground surface: agent-working tools over an isolated
    per-playground filesystem. Mirrors the bitgn EcomRuntime env-tool subset.
    Deliberately excludes any benchmark-specific RPC (no `answer`, no scoring).
    """

    def Read(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadSilent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Tree(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Find(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Exec(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Write(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Context(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EcomEnvServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Read': grpc.unary_unary_rpc_method_handler(
                    servicer.Read,
                    request_deserializer=ecom__agent_dot_v1_dot_ecom__env__pb2.ReadRequest.FromString,
                    response_serializer=ecom__agent_dot_v1_dot_ecom__env__pb2.ReadResponse.SerializeToString,
            ),
            'ReadSilent': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadSilent,
                    request_deserializer=ecom__agent_dot_v1_dot_ecom__env__pb2.ReadRequest.FromString,
                    response_serializer=ecom__agent_dot_v1_dot_ecom__env__pb2.ReadResponse.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=ecom__agent_dot_v1_dot_ecom__env__pb2.ListRequest.FromString,
                    response_serializer=ecom__agent_dot_v1_dot_ecom__env__pb2.ListResponse.SerializeToString,
            ),
            'Tree': grpc.unary_unary_rpc_method_handler(
                    servicer.Tree,
                    request_deserializer=ecom__agent_dot_v1_dot_ecom__env__pb2.TreeRequest.FromString,
                    response_serializer=ecom__agent_dot_v1_dot_ecom__env__pb2.TreeResponse.SerializeToString,
            ),
            'Find': grpc.unary_unary_rpc_method_handler(
                    servicer.Find,
                    request_deserializer=ecom__agent_dot_v1_dot_ecom__env__pb2.FindRequest.FromString,
                    response_serializer=ecom__agent_dot_v1_dot_ecom__env__pb2.FindResponse.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=ecom__agent_dot_v1_dot_ecom__env__pb2.SearchRequest.FromString,
                    response_serializer=ecom__agent_dot_v1_dot_ecom__env__pb2.SearchResponse.SerializeToString,
            ),
            'Stat': grpc.unary_unary_rpc_method_handler(
                    servicer.Stat,
                    request_deserializer=ecom__agent_dot_v1_dot_ecom__env__pb2.StatRequest.FromString,
                    response_serializer=ecom__agent_dot_v1_dot_ecom__env__pb2.StatResponse.SerializeToString,
            ),
            'Exec': grpc.unary_unary_rpc_method_handler(
                    servicer.Exec,
                    request_deserializer=ecom__agent_dot_v1_dot_ecom__env__pb2.ExecRequest.FromString,
                    response_serializer=ecom__agent_dot_v1_dot_ecom__env__pb2.ExecResponse.SerializeToString,
            ),
            'Write': grpc.unary_unary_rpc_method_handler(
                    servicer.Write,
                    request_deserializer=ecom__agent_dot_v1_dot_ecom__env__pb2.WriteRequest.FromString,
                    response_serializer=ecom__agent_dot_v1_dot_ecom__env__pb2.WriteResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=ecom__agent_dot_v1_dot_ecom__env__pb2.DeleteRequest.FromString,
                    response_serializer=ecom__agent_dot_v1_dot_ecom__env__pb2.DeleteResponse.SerializeToString,
            ),
            'Context': grpc.unary_unary_rpc_method_handler(
                    servicer.Context,
                    request_deserializer=ecom__agent_dot_v1_dot_ecom__env__pb2.ContextRequest.FromString,
                    response_serializer=ecom__agent_dot_v1_dot_ecom__env__pb2.ContextResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ecom_agent.v1.EcomEnv', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ecom_agent.v1.EcomEnv', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EcomEnv:
    """EcomEnv is the Playground surface: agent-working tools over an isolated
    per-playground filesystem. Mirrors the bitgn EcomRuntime env-tool subset.
    Deliberately excludes any benchmark-specific RPC (no `answer`, no scoring).
    """

    @staticmethod
    def Read(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ecom_agent.v1.EcomEnv/Read',
            ecom__agent_dot_v1_dot_ecom__env__pb2.ReadRequest.SerializeToString,
            ecom__agent_dot_v1_dot_ecom__env__pb2.ReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadSilent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ecom_agent.v1.EcomEnv/ReadSilent',
            ecom__agent_dot_v1_dot_ecom__env__pb2.ReadRequest.SerializeToString,
            ecom__agent_dot_v1_dot_ecom__env__pb2.ReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ecom_agent.v1.EcomEnv/List',
            ecom__agent_dot_v1_dot_ecom__env__pb2.ListRequest.SerializeToString,
            ecom__agent_dot_v1_dot_ecom__env__pb2.ListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Tree(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ecom_agent.v1.EcomEnv/Tree',
            ecom__agent_dot_v1_dot_ecom__env__pb2.TreeRequest.SerializeToString,
            ecom__agent_dot_v1_dot_ecom__env__pb2.TreeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Find(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ecom_agent.v1.EcomEnv/Find',
            ecom__agent_dot_v1_dot_ecom__env__pb2.FindRequest.SerializeToString,
            ecom__agent_dot_v1_dot_ecom__env__pb2.FindResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ecom_agent.v1.EcomEnv/Search',
            ecom__agent_dot_v1_dot_ecom__env__pb2.SearchRequest.SerializeToString,
            ecom__agent_dot_v1_dot_ecom__env__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ecom_agent.v1.EcomEnv/Stat',
            ecom__agent_dot_v1_dot_ecom__env__pb2.StatRequest.SerializeToString,
            ecom__agent_dot_v1_dot_ecom__env__pb2.StatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Exec(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ecom_agent.v1.EcomEnv/Exec',
            ecom__agent_dot_v1_dot_ecom__env__pb2.ExecRequest.SerializeToString,
            ecom__agent_dot_v1_dot_ecom__env__pb2.ExecResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Write(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ecom_agent.v1.EcomEnv/Write',
            ecom__agent_dot_v1_dot_ecom__env__pb2.WriteRequest.SerializeToString,
            ecom__agent_dot_v1_dot_ecom__env__pb2.WriteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ecom_agent.v1.EcomEnv/Delete',
            ecom__agent_dot_v1_dot_ecom__env__pb2.DeleteRequest.SerializeToString,
            ecom__agent_dot_v1_dot_ecom__env__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Context(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ecom_agent.v1.EcomEnv/Context',
            ecom__agent_dot_v1_dot_ecom__env__pb2.ContextRequest.SerializeToString,
            ecom__agent_dot_v1_dot_ecom__env__pb2.ContextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
